//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace VP_Songbook
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class songbookEntities2 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new songbookEntities2 object using the connection string found in the 'songbookEntities2' section of the application configuration file.
        /// </summary>
        public songbookEntities2() : base("name=songbookEntities2", "songbookEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new songbookEntities2 object.
        /// </summary>
        public songbookEntities2(string connectionString) : base(connectionString, "songbookEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new songbookEntities2 object.
        /// </summary>
        public songbookEntities2(EntityConnection connection) : base(connection, "songbookEntities2")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<category> categories
        {
            get
            {
                if ((_categories == null))
                {
                    _categories = base.CreateObjectSet<category>("categories");
                }
                return _categories;
            }
        }
        private ObjectSet<category> _categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<song> songs
        {
            get
            {
                if ((_songs == null))
                {
                    _songs = base.CreateObjectSet<song>("songs");
                }
                return _songs;
            }
        }
        private ObjectSet<song> _songs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<waitsong> waitsongs
        {
            get
            {
                if ((_waitsongs == null))
                {
                    _waitsongs = base.CreateObjectSet<waitsong>("waitsongs");
                }
                return _waitsongs;
            }
        }
        private ObjectSet<waitsong> _waitsongs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocategories(category category)
        {
            base.AddObject("categories", category);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the songs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosongs(song song)
        {
            base.AddObject("songs", song);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the waitsongs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTowaitsongs(waitsong waitsong)
        {
            base.AddObject("waitsongs", waitsong);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="songbookModel", Name="category")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class category : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new category object.
        /// </summary>
        /// <param name="id_category">Initial value of the id_category property.</param>
        /// <param name="name_category">Initial value of the name_category property.</param>
        public static category Createcategory(global::System.Int32 id_category, global::System.String name_category)
        {
            category category = new category();
            category.id_category = id_category;
            category.name_category = name_category;
            return category;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_category
        {
            get
            {
                return _id_category;
            }
            set
            {
                if (_id_category != value)
                {
                    Onid_categoryChanging(value);
                    ReportPropertyChanging("id_category");
                    _id_category = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_category");
                    Onid_categoryChanged();
                }
            }
        }
        private global::System.Int32 _id_category;
        partial void Onid_categoryChanging(global::System.Int32 value);
        partial void Onid_categoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name_category
        {
            get
            {
                return _name_category;
            }
            set
            {
                Onname_categoryChanging(value);
                ReportPropertyChanging("name_category");
                _name_category = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name_category");
                Onname_categoryChanged();
            }
        }
        private global::System.String _name_category;
        partial void Onname_categoryChanging(global::System.String value);
        partial void Onname_categoryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="songbookModel", Name="song")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class song : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new song object.
        /// </summary>
        /// <param name="id_song">Initial value of the id_song property.</param>
        /// <param name="author">Initial value of the author property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="text">Initial value of the text property.</param>
        /// <param name="id_category">Initial value of the id_category property.</param>
        public static song Createsong(global::System.Int32 id_song, global::System.String author, global::System.String name, global::System.String text, global::System.Int32 id_category)
        {
            song song = new song();
            song.id_song = id_song;
            song.author = author;
            song.name = name;
            song.text = text;
            song.id_category = id_category;
            return song;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_song
        {
            get
            {
                return _id_song;
            }
            set
            {
                if (_id_song != value)
                {
                    Onid_songChanging(value);
                    ReportPropertyChanging("id_song");
                    _id_song = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_song");
                    Onid_songChanged();
                }
            }
        }
        private global::System.Int32 _id_song;
        partial void Onid_songChanging(global::System.Int32 value);
        partial void Onid_songChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String author
        {
            get
            {
                return _author;
            }
            set
            {
                OnauthorChanging(value);
                ReportPropertyChanging("author");
                _author = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("author");
                OnauthorChanged();
            }
        }
        private global::System.String _author;
        partial void OnauthorChanging(global::System.String value);
        partial void OnauthorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_category
        {
            get
            {
                return _id_category;
            }
            set
            {
                Onid_categoryChanging(value);
                ReportPropertyChanging("id_category");
                _id_category = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_category");
                Onid_categoryChanged();
            }
        }
        private global::System.Int32 _id_category;
        partial void Onid_categoryChanging(global::System.Int32 value);
        partial void Onid_categoryChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="songbookModel", Name="waitsong")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class waitsong : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new waitsong object.
        /// </summary>
        /// <param name="id_waitsong">Initial value of the id_waitsong property.</param>
        /// <param name="name_waitsong">Initial value of the name_waitsong property.</param>
        /// <param name="author_waitsong">Initial value of the author_waitsong property.</param>
        /// <param name="id_category">Initial value of the id_category property.</param>
        public static waitsong Createwaitsong(global::System.Int32 id_waitsong, global::System.String name_waitsong, global::System.String author_waitsong, global::System.Int32 id_category)
        {
            waitsong waitsong = new waitsong();
            waitsong.id_waitsong = id_waitsong;
            waitsong.name_waitsong = name_waitsong;
            waitsong.author_waitsong = author_waitsong;
            waitsong.id_category = id_category;
            return waitsong;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_waitsong
        {
            get
            {
                return _id_waitsong;
            }
            set
            {
                if (_id_waitsong != value)
                {
                    Onid_waitsongChanging(value);
                    ReportPropertyChanging("id_waitsong");
                    _id_waitsong = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_waitsong");
                    Onid_waitsongChanged();
                }
            }
        }
        private global::System.Int32 _id_waitsong;
        partial void Onid_waitsongChanging(global::System.Int32 value);
        partial void Onid_waitsongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name_waitsong
        {
            get
            {
                return _name_waitsong;
            }
            set
            {
                Onname_waitsongChanging(value);
                ReportPropertyChanging("name_waitsong");
                _name_waitsong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name_waitsong");
                Onname_waitsongChanged();
            }
        }
        private global::System.String _name_waitsong;
        partial void Onname_waitsongChanging(global::System.String value);
        partial void Onname_waitsongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String author_waitsong
        {
            get
            {
                return _author_waitsong;
            }
            set
            {
                Onauthor_waitsongChanging(value);
                ReportPropertyChanging("author_waitsong");
                _author_waitsong = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("author_waitsong");
                Onauthor_waitsongChanged();
            }
        }
        private global::System.String _author_waitsong;
        partial void Onauthor_waitsongChanging(global::System.String value);
        partial void Onauthor_waitsongChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_category
        {
            get
            {
                return _id_category;
            }
            set
            {
                Onid_categoryChanging(value);
                ReportPropertyChanging("id_category");
                _id_category = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_category");
                Onid_categoryChanged();
            }
        }
        private global::System.Int32 _id_category;
        partial void Onid_categoryChanging(global::System.Int32 value);
        partial void Onid_categoryChanged();

        #endregion

    
    }

    #endregion

    
}
